2020-03-05 13:30:22:963 +0000 [main] INFO org.iota.compass.Coordinator - loaded index 22
2020-03-05 13:30:23:298 +0000 [main] INFO org.iota.compass.Coordinator - Setup
2020-03-05 13:30:23:335 +0000 [main] ERROR org.iota.jota.connection.HttpConnector - Execution of the API call raised exception. IOTA Node not reachable?
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:14265
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:242)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at org.iota.jota.connection.HttpConnector$1.intercept(HttpConnector.java:132)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at org.iota.jota.connection.HttpConnector.wrapCheckedException(HttpConnector.java:240)
	at org.iota.jota.connection.HttpConnector.getNodeInfo(HttpConnector.java:270)
	at org.iota.jota.IotaAPICore.getNodeInfo(IotaAPICore.java:162)
	at org.iota.compass.Coordinator.getNodeInfoWithRetries(Coordinator.java:471)
	at org.iota.compass.Coordinator.setup(Coordinator.java:192)
	at org.iota.compass.Coordinator.main(Coordinator.java:158)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
	... 27 more
2020-03-05 13:30:23:337 +0000 [main] ERROR org.iota.compass.Coordinator - API call failed: 
java.lang.IllegalStateException: Failed to connect to localhost/127.0.0.1:14265
	at org.iota.jota.connection.HttpConnector.wrapCheckedException(HttpConnector.java:263)
	at org.iota.jota.connection.HttpConnector.getNodeInfo(HttpConnector.java:270)
	at org.iota.jota.IotaAPICore.getNodeInfo(IotaAPICore.java:162)
	at org.iota.compass.Coordinator.getNodeInfoWithRetries(Coordinator.java:471)
	at org.iota.compass.Coordinator.setup(Coordinator.java:192)
	at org.iota.compass.Coordinator.main(Coordinator.java:158)
